import type { Locale, Org } from "./_types";

export const COPY = {
  login: {
    pt: {
      kicker: "Acesso",
      title: "Bem-vindo de volta",
      sub: "Entre com seu e-mail de trabalho.",
      email: "E-mail",
      emailPh: "voce@empresa.com",
      cta: "Continuar",
      or: "ou",
      ssoGoogle: "Continuar com Google",
      ssoMs: "Continuar com Microsoft",
    },
    en: {
      kicker: "Access",
      title: "Welcome back",
      sub: "Enter your work email.",
      email: "Email",
      emailPh: "you@company.com",
      cta: "Continue",
      or: "or",
      ssoGoogle: "Continue with Google",
      ssoMs: "Continue with Microsoft",
    },
  },
  email: {
    pt: {
      kicker: "E-mail",
      title: "Entre com seu e-mail",
      sub: "Use o e-mail e a senha da sua conta AwSales.",
      email: "E-mail",
      emailPh: "voce@empresa.com",
      password: "Senha",
      passwordPh: "Digite sua senha",
      keep: "Manter conectado",
      forgot: "Esqueci minha senha",
      cta: "Entrar",
      loadingCta: "Entrando…",
      errPw: "Senha incorreta. Tente novamente ou recupere sua senha.",
      back: "Outras opções",
      or: "ou",
      magicLink: "Receba um link de acesso por e-mail",
      changeEmail: "Usar outro e-mail",
    },
    en: {
      kicker: "Email",
      title: "Sign in with email",
      sub: "Use your AwSales account email and password.",
      email: "Email",
      emailPh: "you@company.com",
      password: "Password",
      passwordPh: "Your password",
      keep: "Keep me signed in",
      forgot: "Forgot password",
      cta: "Sign in",
      loadingCta: "Signing in…",
      errPw: "Wrong password. Try again or recover your password.",
      back: "Other options",
      or: "or",
      magicLink: "Get a sign-in link in your email",
      changeEmail: "Use another email",
    },
  },
  forgot: {
    pt: {
      title: "Esqueceu sua senha?",
      sub: "Informe o e-mail da sua conta. Enviaremos um link seguro para redefinir.",
      email: "E-mail",
      emailPh: "voce@empresa.com",
      cta: "Enviar link de redefinição",
      back: "Voltar ao login",
      kicker: "Recuperação",
    },
    en: {
      title: "Forgot your password?",
      sub: "Enter your account email. We’ll send you a secure reset link.",
      email: "Email",
      emailPh: "you@company.com",
      cta: "Send reset link",
      back: "Back to sign in",
      kicker: "Recovery",
    },
  },
  reset: {
    pt: {
      kicker: "Nova senha",
      title: "Defina uma nova senha",
      sub: "Escolha uma senha forte. Quanto mais longa, melhor — pode usar uma frase secreta com espaços.",
      newPw: "Nova senha",
      confirmPw: "Confirmar nova senha",
      pwPh: "Digite sua nova senha",
      confirmPh: "Digite novamente",
      cta: "Salvar nova senha",
      rule1: "Mínimo de 10 caracteres",
      rule2: "Frase secreta vale — pode usar espaços",
      rule3: "Bloqueamos senhas que já vazaram",
    },
    en: {
      kicker: "New password",
      title: "Set a new password",
      sub: "Pick a strong password. Longer is stronger — a passphrase with spaces works great.",
      newPw: "New password",
      confirmPw: "Confirm new password",
      pwPh: "Type your new password",
      confirmPh: "Type it again",
      cta: "Save new password",
      rule1: "At least 10 characters",
      rule2: "A passphrase works — spaces allowed",
      rule3: "We block leaked passwords",
    },
  },
  verify: {
    pt: {
      kicker: "Verificação",
      title: "Verifique seu e-mail",
      sub: "Enviamos um código de 6 dígitos para",
      code: "Código de verificação",
      cta: "Verificar e continuar",
      resend: "Reenviar em",
      resendReady: "Reenviar código",
      change: "Usar outro e-mail",
      back: "Voltar ao login",
    },
    en: {
      kicker: "Verification",
      title: "Verify your email",
      sub: "We sent a 6-digit code to",
      code: "Verification code",
      cta: "Verify and continue",
      resend: "Resend in",
      resendReady: "Resend code",
      change: "Use another email",
      back: "Back to sign in",
    },
  },
  ssoConnecting: {
    pt: {
      kicker: "Conectando",
      title: "Te direcionando pro acesso da",
      sub: "Aguarde alguns segundos enquanto preparamos sua entrada.",
    },
    en: {
      kicker: "Connecting",
      title: "Sending you to",
      sub: "Hang on for a moment while we set things up.",
    },
  },
  magicSent: {
    pt: {
      kicker: "Link enviado",
      title: "Verifique seu e-mail",
      sub: "Enviamos um link de acesso para",
      hint: "Abra o e-mail e clique no link para entrar. Ele expira em 15 minutos.",
      resend: "Reenviar em",
      resendReady: "Reenviar link",
      change: "Usar outro e-mail",
      back: "Voltar ao login",
    },
    en: {
      kicker: "Link sent",
      title: "Check your email",
      sub: "We sent a sign-in link to",
      hint: "Open the email and click the link to enter. It expires in 15 minutes.",
      resend: "Resend in",
      resendReady: "Resend link",
      change: "Use another email",
      back: "Back to sign in",
    },
  },
  workspace: {
    pt: {
      kicker: "Organização",
      title: "Selecione uma organização",
      sub: "Você faz parte de 3 organizações. Escolha em qual quer entrar agora.",
      cta: "Continuar",
      change: "Trocar de conta",
    },
    en: {
      kicker: "Organization",
      title: "Select an organization",
      sub: "You belong to 3 organizations. Pick the one you want to access now.",
      cta: "Continue",
      change: "Switch account",
    },
  },
  mfaGate: {
    pt: {
      kicker: "Segurança",
      title: "Sua organização exige 2FA",
      sub: "Configure agora a autenticação de dois fatores no seu app autenticador pra continuar acessando.",
      method: "Método",
      methodApp: "App autenticador (TOTP)",
      methodAppDesc: "Google Authenticator, 1Password, Authy ou similar.",
      cta: "Configurar agora",
      already: "Já tenho o app configurado",
      logout: "Sair desta organização",
    },
    en: {
      kicker: "Security",
      title: "Your organization requires 2FA",
      sub: "Set up two-factor authentication in your authenticator app now to keep access.",
      method: "Method",
      methodApp: "Authenticator app (TOTP)",
      methodAppDesc: "Google Authenticator, 1Password, Authy, or similar.",
      cta: "Set up now",
      already: "I already have the app configured",
      logout: "Sign out of this organization",
    },
  },
  mfaSetupApp: {
    pt: {
      kicker: "Passo 1 de 2",
      title: "Configure o app autenticador",
      sub: "Escaneie o QR code no seu app ou copie o segredo manualmente.",
      secretLabel: "Segredo (se não conseguir escanear)",
      copy: "Copiar",
      copied: "Copiado!",
      codeLabel: "Insira o código de 6 dígitos gerado pelo app",
      cta: "Confirmar e continuar",
      back: "Voltar",
    },
    en: {
      kicker: "Step 1 of 2",
      title: "Set up your authenticator app",
      sub: "Scan the QR code in your app or copy the secret manually.",
      secretLabel: "Secret (if you can’t scan)",
      copy: "Copy",
      copied: "Copied!",
      codeLabel: "Enter the 6-digit code generated by the app",
      cta: "Confirm and continue",
      back: "Back",
    },
  },
  mfaBackupCodes: {
    pt: {
      kicker: "Passo 2 de 2",
      title: "Guarde seus códigos de backup",
      sub: "Esses códigos te dão acesso caso você perca o app autenticador. Cada código só pode ser usado uma vez.",
      copy: "Copiar todos",
      copied: "Copiados!",
      download: "Baixar .txt",
      confirm: "Salvei os códigos em um lugar seguro",
      cta: "Concluir configuração",
      warn: "Sem o app e sem os códigos, você perde o acesso à organização.",
    },
    en: {
      kicker: "Step 2 of 2",
      title: "Save your backup codes",
      sub: "These codes grant access if you lose your authenticator app. Each code can be used only once.",
      copy: "Copy all",
      copied: "Copied!",
      download: "Download .txt",
      confirm: "I’ve saved the codes in a safe place",
      cta: "Finish setup",
      warn: "Without the app and the codes, you’ll lose access to the organization.",
    },
  },
  mfaVerify: {
    pt: {
      kicker: "Verificação",
      title: "Confirme sua identidade",
      sub: "Abra seu app autenticador e digite o código de 6 dígitos.",
      code: "Código de verificação",
      cta: "Verificar e continuar",
      useBackup: "Usar um código de backup",
      logout: "Sair",
    },
    en: {
      kicker: "Verification",
      title: "Confirm your identity",
      sub: "Open your authenticator app and enter the 6-digit code.",
      code: "Verification code",
      cta: "Verify and continue",
      useBackup: "Use a backup code",
      logout: "Sign out",
    },
  },
  mfaRecovery: {
    pt: {
      kicker: "Código de backup",
      title: "Use um código de backup",
      sub: "Digite um dos códigos de recuperação que você guardou ao configurar o 2FA.",
      code: "Código de backup",
      codePh: "XXXXX-XXXXX",
      cta: "Verificar e continuar",
      back: "Voltar para o app autenticador",
    },
    en: {
      kicker: "Backup code",
      title: "Use a backup code",
      sub: "Enter one of the recovery codes you saved when setting up 2FA.",
      code: "Backup code",
      codePh: "XXXXX-XXXXX",
      cta: "Verify and continue",
      back: "Back to authenticator app",
    },
  },
  success: {
    pt: {
      title: "Tudo certo!",
      sub: "Redirecionando você para a plataforma…",
      cta: "Entrar agora",
    },
    en: {
      title: "You’re all set!",
      sub: "Redirecting you to the platform…",
      cta: "Enter now",
    },
  },
} satisfies Record<string, Record<Locale, Record<string, string>>>;

export const ORGS: Record<Locale, Org[]> = {
  pt: [
    {
      name: "Artificial Concord",
      meta: "12 membros",
      avatar: "/assets/icon_artificial_concord_organization.png",
    },
    { name: "Fyntra Tecnologia", meta: "8 membros" },
    { name: "AwSales Labs", meta: "Não configurada", pending: true },
  ],
  en: [
    {
      name: "Artificial Concord",
      meta: "12 members",
      avatar: "/assets/icon_artificial_concord_organization.png",
    },
    { name: "Fyntra Tecnologia", meta: "8 members" },
    { name: "AwSales Labs", meta: "Not set up yet", pending: true },
  ],
};
