import type { Locale, Org } from "./_types";

export const COPY = {
  login: {
    pt: {
      kicker: "// acesso",
      title: "Bem-vindo de volta",
      sub: "Entre com seu email de trabalho.",
      email: "Email",
      emailPh: "voce@empresa.com",
      cta: "Continuar",
      or: "ou",
      ssoGoogle: "Continuar com Google",
      ssoMs: "Continuar com Microsoft",
      noAccount: "Ainda não tem conta?",
      signUp: "Primeiro acesso",
    },
    en: {
      kicker: "// access",
      title: "Welcome back",
      sub: "Enter your work email.",
      email: "Email",
      emailPh: "you@company.com",
      cta: "Continue",
      or: "or",
      ssoGoogle: "Continue with Google",
      ssoMs: "Continue with Microsoft",
      noAccount: "Don’t have an account?",
      signUp: "First access",
    },
  },
  email: {
    pt: {
      kicker: "// email",
      title: "Entre com seu email",
      sub: "Use o email e a senha da sua conta AwSales.",
      email: "Email",
      emailPh: "voce@empresa.com",
      password: "Senha",
      passwordPh: "Digite sua senha",
      keep: "Manter conectado",
      forgot: "Esqueci minha senha",
      cta: "Entrar",
      loadingCta: "Entrando…",
      errPw: "Senha incorreta. Tente novamente ou recupere sua senha.",
      back: "Outras opções",
      or: "ou",
      magicLink: "Receba um link de acesso no email",
    },
    en: {
      kicker: "// email",
      title: "Sign in with email",
      sub: "Use your AwSales account email and password.",
      email: "Email",
      emailPh: "you@company.com",
      password: "Password",
      passwordPh: "Your password",
      keep: "Keep me signed in",
      forgot: "Forgot password",
      cta: "Sign in",
      loadingCta: "Signing in…",
      errPw: "Wrong password. Try again or recover your password.",
      back: "Other options",
      or: "or",
      magicLink: "Get a sign-in link in your email",
    },
  },
  forgot: {
    pt: {
      title: "Esqueceu sua senha?",
      sub: "Informe o email da sua conta. Enviaremos um link seguro para redefinir.",
      email: "Email",
      emailPh: "voce@empresa.com",
      cta: "Enviar link de redefinição",
      back: "Voltar ao login",
      kicker: "// recuperação",
    },
    en: {
      title: "Forgot your password?",
      sub: "Enter your account email. We’ll send you a secure reset link.",
      email: "Email",
      emailPh: "you@company.com",
      cta: "Send reset link",
      back: "Back to sign in",
      kicker: "// recovery",
    },
  },
  reset: {
    pt: {
      kicker: "// nova senha",
      title: "Defina uma nova senha",
      sub: "Escolha uma senha forte. Ela deve conter ao menos 8 caracteres, uma letra maiúscula e um número.",
      newPw: "Nova senha",
      confirmPw: "Confirmar nova senha",
      pwPh: "Digite sua nova senha",
      confirmPh: "Digite novamente",
      cta: "Salvar nova senha",
      rule1: "8 caracteres ou mais",
      rule2: "Uma letra maiúscula",
      rule3: "Um número",
    },
    en: {
      kicker: "// new password",
      title: "Set a new password",
      sub: "Pick a strong password. It must have at least 8 characters, one capital letter and one number.",
      newPw: "New password",
      confirmPw: "Confirm new password",
      pwPh: "Type your new password",
      confirmPh: "Type it again",
      cta: "Save new password",
      rule1: "8 characters or more",
      rule2: "One capital letter",
      rule3: "One number",
    },
  },
  verify: {
    pt: {
      kicker: "// verificação",
      title: "Verifique seu email",
      sub: "Enviamos um código de 6 dígitos para",
      code: "Código de verificação",
      cta: "Verificar e continuar",
      resend: "Reenviar em",
      resendReady: "Reenviar código",
      change: "Usar outro email",
      back: "Voltar ao login",
    },
    en: {
      kicker: "// verify",
      title: "Verify your email",
      sub: "We sent a 6-digit code to",
      code: "Verification code",
      cta: "Verify and continue",
      resend: "Resend in",
      resendReady: "Resend code",
      change: "Use another email",
      back: "Back to sign in",
    },
  },
  ssoConnecting: {
    pt: {
      kicker: "// conectando",
      title: "Te direcionando pro acesso da",
      sub: "Aguarde alguns segundos enquanto preparamos sua entrada.",
    },
    en: {
      kicker: "// connecting",
      title: "Sending you to",
      sub: "Hang on for a moment while we set things up.",
    },
  },
  magicSent: {
    pt: {
      kicker: "// link enviado",
      title: "Verifique seu email",
      sub: "Enviamos um link de acesso para",
      hint: "Abra o email e clique no link pra entrar. Ele expira em 15 minutos.",
      resend: "Reenviar em",
      resendReady: "Reenviar link",
      change: "Usar outro email",
      back: "Voltar ao login",
    },
    en: {
      kicker: "// link sent",
      title: "Check your email",
      sub: "We sent a sign-in link to",
      hint: "Open the email and click the link to enter. It expires in 15 minutes.",
      resend: "Resend in",
      resendReady: "Resend link",
      change: "Use another email",
      back: "Back to sign in",
    },
  },
  workspace: {
    pt: {
      kicker: "// organização",
      title: "Selecione uma organização",
      sub: "Você faz parte de 3 organizações. Escolha em qual quer entrar agora.",
      cta: "Continuar",
      change: "Trocar de conta",
    },
    en: {
      kicker: "// organization",
      title: "Select an organization",
      sub: "You belong to 3 organizations. Pick the one you want to access now.",
      cta: "Continue",
      change: "Switch account",
    },
  },
  success: {
    pt: {
      title: "Tudo certo!",
      sub: "Redirecionando você para a plataforma…",
      cta: "Entrar agora",
    },
    en: {
      title: "You’re all set!",
      sub: "Redirecting you to the platform…",
      cta: "Enter now",
    },
  },
} satisfies Record<string, Record<Locale, Record<string, string>>>;

export const ORGS: Record<Locale, Org[]> = {
  pt: [
    {
      name: "Nome da organização",
      meta: "12 membros · admin",
      avatar: "/assets/icon_artificial_concord_organization.png",
    },
    { name: "Fyntra Tecnologia", meta: "8 membros · operador" },
    { name: "AwSales Labs", meta: "1 membro · dono" },
  ],
  en: [
    {
      name: "Organization name",
      meta: "12 members · admin",
      avatar: "/assets/icon_artificial_concord_organization.png",
    },
    { name: "Fyntra Tecnologia", meta: "8 members · operator" },
    { name: "AwSales Labs", meta: "1 member · owner" },
  ],
};
